version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: cloudvault-postgres
    environment:
      POSTGRES_DB: cloudvault
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - cloudvault-network

  app:
    build: .
    container_name: cloudvault-app
    depends_on:
      - postgres
    environment:
      DATABASE_URL: jdbc:postgresql://postgres:5432/cloudvault
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: password
      JWT_SECRET: cloudvault-jwt-secret-key-change-in-production
      STORAGE_TYPE: local
      LOCAL_STORAGE_PATH: /app/uploads
      CORS_ALLOWED_ORIGINS: http://localhost:3000,http://localhost:5173
    ports:
      - "8080:8080"
    volumes:
      - file_uploads:/app/uploads
    networks:
      - cloudvault-network

volumes:
  postgres_data:
  file_uploads:

networks:
  cloudvault-network:
    driver: bridge